plugins { id 'com.android.application' }

android {
    namespace 'com.joyarnold.rorvisualdeck'
    compileSdk 35

    defaultConfig {
        applicationId 'com.joyarnold.rorvisualdeck'
        minSdk 23
        targetSdk 35
        versionCode 32
        versionName '3.2'
    }

    signingConfigs {
        release {
            storeFile file(System.getenv('ROR_RELEASE_KEYSTORE_PATH') ?: "${rootDir}/ror-release.keystore")
            storePassword System.getenv('ROR_RELEASE_KEYSTORE_PASSWORD')
            keyAlias System.getenv('ROR_RELEASE_KEY_ALIAS')
            keyPassword System.getenv('ROR_RELEASE_KEY_PASSWORD')
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            signingConfig signingConfigs.release
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}
