plugins { id 'com.android.application' }

android {
    namespace 'com.joyarnold.rorvisualdeck'
    compileSdk 35

    defaultConfig {
        applicationId 'com.joyarnold.rorvisualdeck'
        minSdk 23
        targetSdk 35
        versionCode 32
        versionName '3.2'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}
