plugins { id 'com.android.application' }

android {
    namespace 'com.nanu.aitradingbot'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nanu.aitradingbot'
        minSdk 23
        targetSdk 35
        versionCode 21
        versionName '6.0-fixed-codex'
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
